---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: ubuntu-13.10
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: centos-6.5
  run_list: recipe[yum-epel]
- name: centos-5.10
  run_list: recipe[yum-epel]

suites:
- name: default
  run_list:
    - recipe[minitest-handler]
    - recipe[msmtp::default]
    - recipe[msmtp::config]
    - recipe[msmtp::no_postfix]
  attributes:
    msmtp:
      host: "smtp.gmail.com"
      port: "587"
      domain: "example.com"
      username: "noreply@example.com"
      from: "noreply@example.com"
      password: "123456"
      default: true
